# Generated by Django 5.2.14 on 2026-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_nm', models.CharField(max_length=100)),
                ('sido', models.CharField(blank=True, max_length=20)),
                ('sigungu', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('elevator_type', models.CharField(blank=True, max_length=50)),
                ('is_operating', models.BooleanField(default=True)),
                ('install_place', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='infrastruct_lat_37dc92_idx'), models.Index(fields=['sido', 'sigungu'], name='infrastruct_sido_bfac0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(choices=[('ramp', '경사로'), ('elevator', '엘리베이터'), ('braille', '점자블록'), ('toilet', '장애인 화장실'), ('parking', '장애인 주차구역'), ('other', '기타')], max_length=20)),
                ('sido', models.CharField(blank=True, max_length=20)),
                ('sigungu', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('ref_date', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='infrastruct_lat_2ebe06_idx'), models.Index(fields=['facility_type'], name='infrastruct_facilit_2742e3_idx'), models.Index(fields=['sido', 'sigungu'], name='infrastruct_sido_c52c07_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sido', models.CharField(blank=True, max_length=20)),
                ('sigungu', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_operating', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='infrastruct_lat_448c3d_idx'), models.Index(fields=['sido', 'sigungu'], name='infrastruct_sido_797f3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=20)),
                ('sigungu', models.CharField(max_length=20)),
                ('road_nm', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('sgn_asp_ordr', models.CharField(blank=True, max_length=50)),
                ('sgn_asp_time', models.CharField(blank=True, max_length=50)),
                ('has_audio', models.BooleanField(default=False)),
                ('has_remndr', models.BooleanField(default=False)),
                ('is_operating', models.BooleanField(default=True)),
                ('manage_no', models.CharField(blank=True, max_length=50)),
                ('ref_date', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='infrastruct_lat_077632_idx'), models.Index(fields=['sido', 'sigungu'], name='infrastruct_sido_c33872_idx'), models.Index(fields=['has_audio'], name='infrastruct_has_aud_e1d2a5_idx')],
            },
        ),
    ]
