# Generated by Django 5.2.14 on 2026-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name_user_nickname_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('small', '작게'), ('medium', '보통'), ('large', '크게'), ('xlarge', '더 크게')], default='medium', max_length=10),
        ),
    ]
