# Generated by Django 5.2.14 on 2026-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='transport_type',
            field=models.CharField(choices=[('walk', '도보'), ('bus', '대중교통'), ('taxi', '택시')], default='walk', max_length=10),
        ),
    ]
