# Generated by Django 5.2.14 on 2026-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
